name: Build Tech Savvy Browser

on:
  push:
    branches: [ main ]
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

        # 🔥 ADD THIS BLOCK
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.11'

      - name: Install Python deps
        run: pip install setuptools

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Build & Publish
        run: npx electron-builder --publish always
        env:
         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}